- id: '1692473210312'
  alias: Record Front Door on Ding
  description: When the doorbell is pressed, start recording
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door_ding
    to: 'on'
  condition: []
  action:
  - service: downloader.download_file
    data:
      url: '{{ state_attr(''camera.front_door'', ''video_url'') }}'
      subdir: '{{ state_attr(''camera.front_door'', ''friendly_name'') }}/{{ now().strftime(''%m-%d-%Y'')
        }}'
      filename: '{{ now().strftime(''%H-%M-%S'') }}.mp4'
  mode: single
- id: '1692473360284'
  alias: Play Alexa on Front Door motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.front_door_motion
    to: 'on'
  condition:
  - condition: and
    conditions:
    - condition: time
      after: '22:00:00'
      before: 06:00:00
      weekday:
      - sun
      - mon
      - tue
      - wed
      - thu
      - fri
      - sat
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.foyer_shelly_switch_channel_1
  - delay:
      hours: 0
      minutes: 20
      seconds: 0
      milliseconds: 0
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.foyer_shelly_switch_channel_1
  mode: single
- id: '1692474522460'
  alias: Record Betty's Back Door on Motion
  description: ''
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.back_door_motion
    to: 'on'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 2
      seconds: 0
      milliseconds: 0
  - service: downloader.download_file
    data:
      url: '{{ state_attr(''camera.back_door'', ''video_url'') }}'
      subdir: '{{ state_attr(''camera.back_door'', ''friendly_name'') }}/{{ now().strftime(''%m-%d-%Y'')
        }}'
      filename: '{{ now().strftime(''%H-%M-%S'') }}.mp4'
  mode: single
- id: '1692474759816'
  alias: Front Porch Lights on After Sunset
  description: ''
  trigger:
  - platform: sun
    event: sunset
    offset: 0
  condition: []
  action:
  - service: switch.turn_on
    data: {}
    target:
      entity_id: switch.foyer_shelly_switch_channel_1
  mode: single
- id: '1692476340195'
  alias: Notify Alexa Motion Detected
  description: ''
  trigger:
  - platform: state
    entity_id:
    - sensor.last_motion_location
  condition:
  - condition: time
    after: 08:30:00
    before: '23:00:00'
  action:
  - service: script.motion_detected
    data: {}
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
  mode: single
- id: '1692504216581'
  alias: Front Porch Light Off after 11
  description: ''
  trigger:
  - platform: time
    at: '23:00:00'
  condition: []
  action:
  - service: switch.turn_off
    data: {}
    target:
      entity_id: switch.foyer_shelly_switch_channel_1
  mode: single
